version: 2

models:
  - name: stg_orders
    description: >
      Cleansed and enriched version of `bronze_orders`.
      Includes computed metrics such as profit and total_price at the order level.
      Used in customer and product-level profitability reporting.
    tags: ['silver']
    meta:
      owner: 'analytics_team'
      sensitivity: 'medium'
    columns:
      - name: order_id
        description: "Unique identifier for the order."
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Foreign key to the customer who placed the order."
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: order_status
        description: "Current status of the order (e.g., 'Completed', 'Shipped')."
      - name: total_price
        description: "Total price for the order before taxes or discounts."
      - name: profit
        description: "Calculated profit for the order (total revenue minus cost)."

  - name: stg_customers
    description: >
      Standardized customer dataset from `bronze_customers`, with nulls removed and region enrichment via `stg_country`.
      Supports segmentation and geo-based profitability analysis.
    tags: ['silver']
    meta:
      owner: 'analytics_team'
      sensitivity: 'medium'
    columns:
      - name: customer_id
        description: "Unique identifier for each customer."
        tests:
          - unique
          - not_null
      - name: customer_name
        description: "Full name of the customer."
      - name: country
        description: "Customer's country of residence."
      - name: customer_region
        description: "Mapped region based on customer's country."
        tests:
          - not_null

  - name: stg_products
    description: >
      Deduplicated and normalized product data from `bronze_products`.
      Used in product profit analysis and dimensional modeling.
    tags: ['silver']
    meta:
      owner: 'analytics_team'
      sensitivity: 'low'
    columns:
      - name: product_id
        description: "Unique identifier for the product."
        tests:
          - unique
          - not_null
      - name: product_name
        description: "Name of the product."
      - name: product_category
        description: "Top-level product classification (e.g., Electronics, Furniture)."
      - name: product_subcategory
        description: "More specific product grouping under each category."

  - name: stg_payments
    description: >
      Filtered dataset from `bronze_payments` including only successful transactions.
      Used for payment analysis, success rates, and unpaid order audits.
    tags: ['silver']
    meta:
      owner: 'finance_team'
      sensitivity: 'high'
    columns:
      - name: payment_id
        description: "Unique identifier for the payment transaction."
        tests:
          - unique
          - not_null
      - name: order_id
        description: "Foreign key to the associated order."
        tests:
          - not_null
          - relationships:
              to: ref('stg_orders')
              field: order_id
      - name: payment_status
        description: "Status of the payment; expected to be 'Success'."
        tests:
          - accepted_values:
              values: ['Success']
              quote: true
      - name: payment_amount
        description: "Monetary amount of the successful payment."

  - name: stg_country
    description: >
      Reference model for mapping countries to geographic regions.
      Used to enrich customer data and support region-based reporting.
    tags: ['silver', 'reference']
    meta:
      owner: 'data_ops_team'
      sensitivity: 'low'
    columns:
      - name: country
        description: "Country name (used as a key to join with customer data)."
        tests:
          - unique
          - not_null
      - name: region
        description: "Region or zone that the country belongs to (e.g., North America, APAC)."
        tests:
          - not_null
